# SPDX-FileCopyrightText: : Ludwig Hülk © Reiner Lemoine Institut <https://github.com/Ludee>
# SPDX-License-Identifier: CC0-1.0

# exclude webdevelopement build artefacts
exclude: ^.*(.min.js|.min.css)$

repos:
  # Pre-commit-hooks - Out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          [
            "--autofix", # Autofix JSONs
          ]
      - id: check-added-large-files
        args: [ "--maxkb=1500" ]

  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black

  # isort - Sort Python imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

  # Ruff - Fast Python linter, written in Rust
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.284'
    hooks:
    - id: ruff

  # Flake8 - Python linter with PyFlakes and pycodestyle
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: ["--max-line-length=88", "--ignore=E20,W503,W605"] # black compatible

  # mypy mirror - Added static types to Python (Python is dynamically typed)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
    - id: mypy
      additional_dependencies:
        - 'sqlalchemy'
        - 'types-requests'

  # mirrors-prettier - Formatting for other files then python scripts
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.2'
    hooks:
    - id: prettier
      files: \.(css|less|md|json|sql)$

  # REUSE Software - Make licensing easy for humans and machines alike
  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.0.0
    hooks:
    - id: reuse

  # Linter for JavaScript
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.38.0
  #   hooks:
  #     - id: eslint
  #       additional_dependencies:
  #       - eslint@8.14.0
  #       - eslint-config-google@0.14.0
  #       - eslint-plugin-jsdoc@39.2.9
  #       args: ["--fix"]
