# Project
site_name: Super-Repo Documentation
site_url: 
site_description: Write your documentation in Markdown and create a static page for your developer and user community

# Repository
repo_name: rl-institut/super-repo
repo_url: https://github.com/rl-institut/super-repo
docs_dir: docs

# Configuration
theme:
  name: material
  logo: img/logo_rli_small.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.tracking
    - navigation.top
    - toc.follow

# extensions 
markdown_extensions:
  - admonition

plugins:
- mkdocstrings:

# Customization
extra:
  generator: false

extra_css:
  - css/extra.css

# Navigation
nav:
  - Home: index.md
  - Development:
    - Collaboration:
      - collaboration/index.md
      - License: collaboration/license.md
      - Citation: collaboration/citation.md
      - Contributing: collaboration/contributing.md
      - Users: collaboration/users.md
      - Code of Conduct: collaboration/code_of_conduct.md
    - Git:
      - git/index.md
    - Documentation:
      - documentation/index.md
    - Release:
      - release/index.md
  - Code Documentation:
    - Install:
      - git/index.md
    - Guidelines:
      - git/code-guidelines.md
    - Workflows:
      - Test Driven Development: 
        - git/test-driven-developement-workflow.md

